export const layerConstant = {
    GET_ALL_REQUEST: 'GET_ALL_LAYER_REQUEST',
    GET_ALL_SUCCESS: 'GET_ALL_LAYER_SUCCESS',
    GET_ALL_FAIL: 'GET_ALL_LAYER_FAIL',
    GET_FEATURE_INFO_REQUEST: 'GET_FEATURE_INFO_REQUEST',
    GET_FEATURE_INFO_SUCCESS: 'GET_FEATURE_INFO_SUCCESS',
    GET_FEATURE_INFO_FAIL: 'GET_FEATURE_INFO_FAIL',
};

export default layerConstant;