export const poiConstant = {
    GET_ALL_REQUEST: 'GET_ALL_POI_REQUEST',
    GET_ALL_SUCCESS: 'GET_ALL_POI_SUCCESS',
    GET_ALL_FAIL: 'GET_ALL_POI_FAIL',
    GET_REQUEST: 'GET_POI_REQUEST',
    GET_SUCCESS: 'GET_POI_SUCCESS',
    GET_FAIL: 'GET_POI_FAIL',
    ADD_REQUEST: 'ADD_POI_REQUEST',
    ADD_SUCCESS: 'ADD_POI_SUCCESS',
    ADD_FAIL: 'ADD_POI_FAIL',
    UPDATE_REQUEST: 'UPDATE_POI_REQUEST',
    UPDATE_SUCCESS: 'UPDATE_POI_SUCCESS',
    UPDATE_FAIL: 'UPDATE_POI_FAIL',
    RESET: 'RESET_POI',
};

export default poiConstant;