export const uiConstant = {
    OPEN_BOTTOM_PANEL: 'OPEN_BOTTOM_PANEL',
    CLOSE_BOTTOM_PANEL: 'CLOSE_BOTTOM_PANEL',
    MINIMIZE_BOTTOM_PANEL: 'MINIMIZE_BOTTOM_PANEL',
    MAXIMIZE_BOTTOM_PANEL: 'MAXIMIZE_BOTTOM_PANEL',
    OPEN_RIGHT_PANEL: 'OPEN_RIGHT_PANEL',
    CLOSE_RIGHT_PANEL: 'CLOSE_RIGHT_PANEL',
};

export default uiConstant;