//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal.Entities
{
    
    
    [core.Attributes.TableAttribute(Name="layer_control")]
    [Newtonsoft.Json.JsonObjectAttribute("LayerControl")]
    public sealed class LayerControl : core.Bases.EntityBase
    {
        
        private long _LayerId;
        
        private long _ParentLayerId;
        
        private long _UserId;
        
        private long _Id;
        
        private string _GeoserverLayerName;
        
        private string _LayerLabel;
        
        private string _CqlFilter;
        
        private bool _Status;
        
        private bool _Checked;
        
        private int _Order;
        
        private int _MinVisibleLevel;
        
        private int _MaxVisibleLevel;
        
        private int _Opacity;
        
        private string _GeoserverAddress;
        
        private string _EntityName;
        
        [core.Attributes.ColumnAttribute(Name="layer_id", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("LayerId")]
        public long LayerId
        {
            get
            {
                return this._LayerId;
            }
            set
            {
                this._LayerId = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="parent_layer_id", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("ParentLayerId")]
        public long ParentLayerId
        {
            get
            {
                return this._ParentLayerId;
            }
            set
            {
                this._ParentLayerId = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="user_id", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("UserId")]
        public long UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this._UserId = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="id", Identity=true, Spatial=false, SequenceName="layer_control_seq")]
        [Newtonsoft.Json.JsonPropertyAttribute("Id")]
        public override long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="geoserver_layer_name", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("GeoserverLayerName")]
        public string GeoserverLayerName
        {
            get
            {
                return this._GeoserverLayerName;
            }
            set
            {
                this._GeoserverLayerName = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="layer_label", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("LayerLabel")]
        public string LayerLabel
        {
            get
            {
                return this._LayerLabel;
            }
            set
            {
                this._LayerLabel = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="cql_filter", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("CqlFilter")]
        public string CqlFilter
        {
            get
            {
                return this._CqlFilter;
            }
            set
            {
                this._CqlFilter = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="status", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("Status")]
        public bool Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this._Status = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="checked", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("Checked")]
        public bool Checked
        {
            get
            {
                return this._Checked;
            }
            set
            {
                this._Checked = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="order", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("Order")]
        public int Order
        {
            get
            {
                return this._Order;
            }
            set
            {
                this._Order = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="min_visible_level", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("MinVisibleLevel")]
        public int MinVisibleLevel
        {
            get
            {
                return this._MinVisibleLevel;
            }
            set
            {
                this._MinVisibleLevel = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="max_visible_level", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("MaxVisibleLevel")]
        public int MaxVisibleLevel
        {
            get
            {
                return this._MaxVisibleLevel;
            }
            set
            {
                this._MaxVisibleLevel = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="opacity", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("Opacity")]
        public int Opacity
        {
            get
            {
                return this._Opacity;
            }
            set
            {
                this._Opacity = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="geoserver_adress", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("GeoserverAddress")]
        public string GeoserverAddress
        {
            get
            {
                return this._GeoserverAddress;
            }
            set
            {
                this._GeoserverAddress = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="entity_name", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("EntityName")]
        public string EntityName
        {
            get
            {
                return this._EntityName;
            }
            set
            {
                this._EntityName = value;
            }
        }
    }
}
