//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal.Entities
{
    
    
    [core.Attributes.TableAttribute(Name="role_permission")]
    [Newtonsoft.Json.JsonObjectAttribute("RolePermission")]
    public sealed class RolePermission : core.Bases.EntityBase
    {
        
        private long _Id;
        
        private long _RoleId;
        
        private long _PermissionId;
        
        [core.Attributes.ColumnAttribute(Name="id", Identity=true, Spatial=false, SequenceName="role_permission_seq")]
        [Newtonsoft.Json.JsonPropertyAttribute("Id")]
        public override long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="role_id", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("RoleId")]
        public long RoleId
        {
            get
            {
                return this._RoleId;
            }
            set
            {
                this._RoleId = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="permission_id", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("PermissionId")]
        public long PermissionId
        {
            get
            {
                return this._PermissionId;
            }
            set
            {
                this._PermissionId = value;
            }
        }
    }
}
