//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal.Entities
{
    
    
    [core.Attributes.TableAttribute(Name="v_user_i_o_log")]
    [Newtonsoft.Json.JsonObjectAttribute("VUserIOLog")]
    public sealed class VUserIOLog : core.Bases.EntityBase
    {
        
        private string _Name;
        
        private long _Id;
        
        private string _Type;
        
        private System.Nullable<System.DateTime> _Date;
        
        private string _UserName;
        
        private string _Surname;
        
        private int _TypeId;
        
        [core.Attributes.ColumnAttribute(Name="name", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this._Name = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="id", Identity=true, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("Id")]
        public override long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="type", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("Type")]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this._Type = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="date", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("Date")]
        public System.Nullable<System.DateTime> Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this._Date = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="user_name", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("UserName")]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this._UserName = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="surname", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("Surname")]
        public string Surname
        {
            get
            {
                return this._Surname;
            }
            set
            {
                this._Surname = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="type_id", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("TypeId")]
        public int TypeId
        {
            get
            {
                return this._TypeId;
            }
            set
            {
                this._TypeId = value;
            }
        }
    }
}
