//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal.Entities
{
    
    
    [core.Attributes.TableAttribute(Name="action_log")]
    [Newtonsoft.Json.JsonObjectAttribute("Action Log")]
    public sealed class ActionLog : core.Bases.EntityBase
    {
        
        private long _Id;
        
        private string _Ip;
        
        private string _Controller;
        
        private System.Nullable<System.DateTime> _Date;
        
        private string _Action;
        
        private string _Explanation;
        
        private long _UserId;
        
        [core.Attributes.ColumnAttribute(Name="id", Identity=true, Spatial=false, SequenceName="action_log_seq")]
        [Newtonsoft.Json.JsonPropertyAttribute("Id")]
        public override long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="ip", Identity=false, Spatial=false, SequenceName=null)]
        [Newtonsoft.Json.JsonPropertyAttribute("Ip")]
        public string Ip
        {
            get
            {
                return this._Ip;
            }
            set
            {
                this._Ip = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="controller", Identity=false, Spatial=false, SequenceName=null)]
        [Newtonsoft.Json.JsonPropertyAttribute("Controller")]
        public string Controller
        {
            get
            {
                return this._Controller;
            }
            set
            {
                this._Controller = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="date", Identity=false, Spatial=false, SequenceName=null)]
        [Newtonsoft.Json.JsonPropertyAttribute("Date")]
        public System.Nullable<System.DateTime> Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this._Date = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="action", Identity=false, Spatial=false, SequenceName=null)]
        [Newtonsoft.Json.JsonPropertyAttribute("Action")]
        public string Action
        {
            get
            {
                return this._Action;
            }
            set
            {
                this._Action = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="explanation", Identity=false, Spatial=false, SequenceName=null)]
        [Newtonsoft.Json.JsonPropertyAttribute("Explanation")]
        public string Explanation
        {
            get
            {
                return this._Explanation;
            }
            set
            {
                this._Explanation = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="user_id", Identity=false, Spatial=false, SequenceName=null)]
        [Newtonsoft.Json.JsonPropertyAttribute("User Id")]
        public long UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this._UserId = value;
            }
        }
    }
}
