//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal.Models
{
    using Microsoft.EntityFrameworkCore;
    
    
    public sealed partial class DalDbContext : Microsoft.EntityFrameworkCore.DbContext
    {
        
        public DbSet<dal.Entities.Province> Province { get; set; }//;
        
        public DbSet<dal.Entities.District> District { get; set; }//;
        
        public DbSet<dal.Entities.Neighborhood> Neighborhood { get; set; }//;
        
        public DbSet<dal.Entities.LayerControl> LayerControl { get; set; }//;
        
        public DbSet<dal.Entities.UserLog> UserLog { get; set; }//;
        
        public DbSet<dal.Entities.Permission> Permission { get; set; }//;
        
        public DbSet<dal.Entities.Role> Role { get; set; }//;
        
        public DbSet<dal.Entities.RolePermission> RolePermission { get; set; }//;
        
        public DbSet<dal.Entities.UserRole> UserRole { get; set; }//;
        
        public DbSet<dal.Entities.Setting> Setting { get; set; }//;
        
        public DbSet<dal.Entities.User> User { get; set; }//;
        
        public DbSet<dal.Entities.VAddress> VAddress { get; set; }//;
        
        public DbSet<dal.Entities.VUserIOLog> VUserIOLog { get; set; }//;
        
        public DbSet<dal.Entities.ActionLog> ActionLog { get; set; }//;
        
        public DbSet<dal.Entities.Poi> Poi { get; set; }//;
    }
}
