//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal.Entities
{
    
    
    [core.Attributes.TableAttribute(Name="neighborhood")]
    [Newtonsoft.Json.JsonObjectAttribute("Mahalle")]
    public sealed class Neighborhood : core.Bases.EntityBase
    {
        
        private long _Id;
        
        private string _Name;
        
        private NetTopologySuite.Geometries.Geometry _Geoloc;
        
        private string _FullName;
        
        private long _ParentCode;
        
        private long _UavtCode;
        
        private int _TypeDefid;
        
        [core.Attributes.ColumnAttribute(Name="id", Identity=true, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("Id")]
        public override long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="name", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("Ad")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this._Name = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="geoloc", Identity=false, Spatial=true, SequenceName="")]
        [Newtonsoft.Json.JsonIgnoreAttribute()]
        public NetTopologySuite.Geometries.Geometry Geoloc
        {
            get
            {
                return this._Geoloc;
            }
            set
            {
                this._Geoloc = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="full_name", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("Tam Adı")]
        [core.Attributes.InfoAttribute()]
        public string FullName
        {
            get
            {
                return this._FullName;
            }
            set
            {
                this._FullName = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="parent_code", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("ParentCode")]
        public long ParentCode
        {
            get
            {
                return this._ParentCode;
            }
            set
            {
                this._ParentCode = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="uavt_code", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("Uavt Kodu")]
        public long UavtCode
        {
            get
            {
                return this._UavtCode;
            }
            set
            {
                this._UavtCode = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="type_defid", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("Tip Id")]
        public int TypeDefid
        {
            get
            {
                return this._TypeDefid;
            }
            set
            {
                this._TypeDefid = value;
            }
        }
    }
}
