//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal.Entities
{
    
    
    [core.Attributes.TableAttribute(Name="poi")]
    [Newtonsoft.Json.JsonObjectAttribute("Poi")]
    public sealed class Poi : core.Bases.EntityBase
    {
        
        private string _Name;
        
        private long _Id;
        
        private NetTopologySuite.Geometries.Geometry _Geoloc;
        
        [core.Attributes.ColumnAttribute(Name="name", Identity=false, Spatial=false, SequenceName=null)]
        [Newtonsoft.Json.JsonPropertyAttribute("Name")]
        [core.Attributes.InfoAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this._Name = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="id", Identity=true, Spatial=false, SequenceName="poi_seq")]
        [Newtonsoft.Json.JsonPropertyAttribute("Id")]
        public override long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="geoloc", Identity=false, Spatial=true, SequenceName=null)]
        [Newtonsoft.Json.JsonIgnoreAttribute()]
        public NetTopologySuite.Geometries.Geometry Geoloc
        {
            get
            {
                return this._Geoloc;
            }
            set
            {
                this._Geoloc = value;
            }
        }
    }
}
