//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal.Entities
{
    
    
    [core.Attributes.TableAttribute(Name="user_")]
    [Newtonsoft.Json.JsonObjectAttribute("Kullanıcı")]
    public sealed class User : core.Bases.EntityBase
    {
        
        private long _Id;
        
        private string _Username;
        
        private string _Name;
        
        private string _Surname;
        
        private string _Mail;
        
        private string _Password;
        
        private string _Description;
        
        private bool _Status;
        
        private bool _FirstLogin;
        
        private bool _IsDeleted;
        
        private bool _Locked;
        
        private int _Retries;
        
        private System.Nullable<System.DateTime> _LockedDate;
        
        private long _UserId;
        
        [core.Attributes.ColumnAttribute(Name="id", Identity=true, Spatial=false, SequenceName="user_seq")]
        [Newtonsoft.Json.JsonPropertyAttribute("Id")]
        public override long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="username", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("Username")]
        public string Username
        {
            get
            {
                return this._Username;
            }
            set
            {
                this._Username = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="name", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this._Name = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="surname", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("Surname")]
        public string Surname
        {
            get
            {
                return this._Surname;
            }
            set
            {
                this._Surname = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="mail", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("Mail")]
        public string Mail
        {
            get
            {
                return this._Mail;
            }
            set
            {
                this._Mail = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="password", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("Password")]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this._Password = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="description", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("Description")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this._Description = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="status", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("Status")]
        public bool Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this._Status = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="first_login", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("FirstLogin")]
        public bool FirstLogin
        {
            get
            {
                return this._FirstLogin;
            }
            set
            {
                this._FirstLogin = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="is_deleted", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("IsDeleted")]
        public bool IsDeleted
        {
            get
            {
                return this._IsDeleted;
            }
            set
            {
                this._IsDeleted = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="locked", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("Locked")]
        public bool Locked
        {
            get
            {
                return this._Locked;
            }
            set
            {
                this._Locked = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="retries", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("Retries")]
        public int Retries
        {
            get
            {
                return this._Retries;
            }
            set
            {
                this._Retries = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="locked_date", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("LockedDate")]
        public System.Nullable<System.DateTime> LockedDate
        {
            get
            {
                return this._LockedDate;
            }
            set
            {
                this._LockedDate = value;
            }
        }
        
        [core.Attributes.ColumnAttribute(Name="user_id", Identity=false, Spatial=false, SequenceName="")]
        [Newtonsoft.Json.JsonPropertyAttribute("UserId")]
        public long UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this._UserId = value;
            }
        }
    }
}
